server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location = /health/live { access_log off; return 200 'healthy'; }
    location /api/ { return 404; }
    location /assets/ { try_files $uri =404; }
    location / { try_files $uri $uri/ /index.html; }
}
